platform:ios,'8.0'
target 'QXDSImageBrowse' do

pod 'YYCache', :git => 'https://github.com/labi3285/YYCache.git'
pod 'YYImage', :git => 'https://github.com/labi3285/YYImage.git'
pod 'YYWebImage', :git => 'https://github.com/labi3285/YYWebImage.git'

end
